### ISSUE TITLE
converting to ONNX 

### ISSUE THREAD

**Issue by doudoudiandiandou** [chequanghuy/TwinLiteNet#3]
"Hello, do you have scripts for converting to ONNX and TRT?"

**Comment by chequanghuy** [comment]
I have updated them in the export.py file. You can test it now.

**Comment by uyolo-ai** [comment]
export.py file with some bugs

https://github.com/chequanghuy/TwinLiteNet/blob/45d9d94c01ae988b0d5ed0bbe5949eb00db45654/export.py#L7

should be replaced with `from model.TwinLite import TwinLiteNet as Net`

https://github.com/chequanghuy/TwinLiteNet/blob/45d9d94c01ae988b0d5ed0bbe5949eb00db45654/export.py#L155-L156

should remove `nargs='+'`

**Comment by chequanghuy** [comment]
@uyolo1314   Thank you for your helpful comments. I have fixed them.
