### ISSUE TITLE
main.py does not exist

### ISSUE THREAD

**Issue by balnarendrasapa** [chequanghuy/TwinLiteNet#6]
when i run main.py as stated in readme, python says that the file does not exists. I am wondering if it is train.py.

**Comment by bg-szy** [comment]
python3 test_image.py

**Comment by bg-szy** [comment]
> when i run main.py as stated in readme, python says that the file does not exists. I am wondering if it is train.py.
python3 test_image.py

**Comment by reza-nouri-9696** [comment]
yes it is train.py
